#!/bin/bash
set -e

function cp_gitignore {
  cd $1
  cp .gitignore gitignore.txt
  cd ../../../
}

cp_gitignore templates/multi-module/client
cp_gitignore templates/multi-module/server

cp_gitignore templates/single-module/client
cp_gitignore templates/single-module/server
